; --- CONFIGURAÇÃO CHANSPY (PRISMA TELECOM) ---
[app-chanspy]
exten => 555,1,Macro(user-callerid,)
exten => 555,n,Answer
exten => 555,n,Wait(1)
exten => 555,n,Authenticate(1234)
exten => 555,n,Wait(1)
exten => 555,n,ChanSpy()
exten => 555,n,Hangup
exten => _555X.,1,Macro(user-callerid,)
exten => _555X.,n,Answer
exten => _555X.,n,Wait(1)
exten => _555X.,n,Authenticate(1234)
exten => _555X.,n,Wait(1)
exten => _555X.,n,ChanSpy(SIP/${EXTEN:3})
exten => _555X.,n,Hangup
